
import "./globals.css";
import { Assistant } from "next/font/google"; 


const assistantFont = Assistant({
  subsets: ["latin"],
  variable: "--font-assistant",
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${assistantFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
